###
PUT http://localhost:7777/users/hhhhhh HTTP/1.1
content-type: application/json

{"players": 
[{
    "name": "hi",
    "total": 50,
    "id": 2,
    "dealer": false
}, {
    "name": "larry",
    "total": 100
}
]}

###
GET http://localhost:7777/users/larry HTTP/1.1


###
DELETE http://localhost:7777/users


