###
PUT http://localhost:7777/users/joe HTTP/1.1
content-type: application/json

{"players": 
[{
    "name": "joe",
    "amount": 50,
    "id": 2,
    "dealer": false
}, {
    "name": "larry",
    "amount": 100
}
]}

###
GET http://localhost:7777/users/joe HTTP/1.1


###
DELETE http://localhost:7777/users


